---

- name: graphite migrate
  # command: graphite-manage syncdb --noinput
  shell: export PYTHONPATH=/opt/graphite/webapp/; /opt/graphite/bin/python /opt/graphite/bin/django-admin.py migrate --noinput --settings=graphite.settings
  become: True
  become_user: _graphite
  when: graphite_manage_db

- name: uwsgi restart
  service: name=uwsgi state=restarted
  when: uwsgi_manage_service

- name: carbon restart
  service: name=carbon-cache state=restarted
  when: graphite_manage_service

- name: carbon stop
  service: name=carbon-cache state=stopped
